/* tslint:disable */
/* eslint-disable */
/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseError
 */
export interface BaseError {
    /**
     * 
     * @type {string}
     * @memberof BaseError
     */
    readonly message: string;
    /**
     * 
     * @type {string}
     * @memberof BaseError
     */
    readonly code: string;
}

/**
 * Check if a given object implements the BaseError interface.
 */
export function instanceOfBaseError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function BaseErrorFromJSON(json: any): BaseError {
    return BaseErrorFromJSONTyped(json, false);
}

export function BaseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
    };
}

export function BaseErrorToJSON(value?: BaseError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

