/* tslint:disable */
/* eslint-disable */
/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ForbiddenError403ResponseError } from './ForbiddenError403ResponseError';
import {
    ForbiddenError403ResponseErrorFromJSON,
    ForbiddenError403ResponseErrorFromJSONTyped,
    ForbiddenError403ResponseErrorToJSON,
} from './ForbiddenError403ResponseError';

/**
 * 
 * @export
 * @interface ForbiddenError403Response
 */
export interface ForbiddenError403Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ForbiddenError403Response
     */
    readonly data: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ForbiddenError403Response
     */
    readonly success: boolean;
    /**
     * 
     * @type {ForbiddenError403ResponseError}
     * @memberof ForbiddenError403Response
     */
    error: ForbiddenError403ResponseError;
}

/**
 * Check if a given object implements the ForbiddenError403Response interface.
 */
export function instanceOfForbiddenError403Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function ForbiddenError403ResponseFromJSON(json: any): ForbiddenError403Response {
    return ForbiddenError403ResponseFromJSONTyped(json, false);
}

export function ForbiddenError403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenError403Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'success': json['success'],
        'error': ForbiddenError403ResponseErrorFromJSON(json['error']),
    };
}

export function ForbiddenError403ResponseToJSON(value?: ForbiddenError403Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ForbiddenError403ResponseErrorToJSON(value.error),
    };
}

