/* tslint:disable */
/* eslint-disable */
/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UnauthorizedError401ResponseError } from './UnauthorizedError401ResponseError';
import {
    UnauthorizedError401ResponseErrorFromJSON,
    UnauthorizedError401ResponseErrorFromJSONTyped,
    UnauthorizedError401ResponseErrorToJSON,
} from './UnauthorizedError401ResponseError';

/**
 * 
 * @export
 * @interface UnauthorizedError401Response
 */
export interface UnauthorizedError401Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof UnauthorizedError401Response
     */
    readonly data: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UnauthorizedError401Response
     */
    readonly success: boolean;
    /**
     * 
     * @type {UnauthorizedError401ResponseError}
     * @memberof UnauthorizedError401Response
     */
    error: UnauthorizedError401ResponseError;
}

/**
 * Check if a given object implements the UnauthorizedError401Response interface.
 */
export function instanceOfUnauthorizedError401Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function UnauthorizedError401ResponseFromJSON(json: any): UnauthorizedError401Response {
    return UnauthorizedError401ResponseFromJSONTyped(json, false);
}

export function UnauthorizedError401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedError401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'success': json['success'],
        'error': UnauthorizedError401ResponseErrorFromJSON(json['error']),
    };
}

export function UnauthorizedError401ResponseToJSON(value?: UnauthorizedError401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': UnauthorizedError401ResponseErrorToJSON(value.error),
    };
}

